title: Safia Zaki
description: Étudiante en Systèmes Intelligents & Recherche Opérationnelle
theme: jekyll-theme-architect # Un thème moderne avec une barre latérale élégante
logo: https://github.com/zakisofia.png
show_downloads: false
google_analytics:
