title: "Zakisofia | Étudiante en Systèmes Intelligents"
description: "Parcours d’excellence – Intelligence Artificielle, Recherche Opérationnelle & Optimisation"
theme: jekyll-theme-modernist
show_downloads: false


