title: "Zakisofia | Étudiante en Systèmes Intelligents"
description: "Parcours d’excellence en Intelligence Artificielle & Recherche Opérationnelle"
theme: jekyll-theme-architect
show_downloads: false

